#!/usr/bin/perl

use FindBin;

use lib ("$FindBin::Bin/../../lib",);

use Sid::Plugin::Script;

use strict;
use warnings;

my %dispatch = (
    'linux' => \&linux,
	'darwin' => \&darwin,
);

my $s = Sid::Plugin::Script->new;

my $entity = $s->find_entity(
    type => 'system',
    primary_id => $s->agent_id,
);
die "No entity!" unless defined $entity;

my $os = $entity->find_field(field => 'perlos');
die "No OS!" unless defined $os;

$s->exit_zero unless exists($dispatch{$os});

$entity = $dispatch{$os}($s, $entity);

$s->update_entity(entity => $entity);

$s->exit_zero;

sub linux {
    my $s = shift;
    my $entity = shift;

    $entity->add_field_from_exec(
        field => 'hostname',
        command => 'hostname',
        do_chomp => 1
    );
    $entity->add_field_from_exec(
        field => 'fqdn',
        command => 'hostname --fqdn',
        do_chomp => 1
    );

    return $entity;
}

sub darwin {
	my $s = shift;
	my $entity = shift;
	
	$entity->add_field_from_exec(
		field => 'hostname',
		command => 'hostname -s',
		do_chomp => 1,
	);
	
	return $entity;
}