#!/usr/bin/perl

use FindBin;

use lib ("$FindBin::Bin/../../lib",);

use Sid::Plugin::Script;

use strict;
use warnings;

my %dispatch = (
    'linux' => \&linux,
);

my $s = Sid::Plugin::Script->new;

my $entity = $s->find_entity(
    type => 'system',
    primary_id => $s->agent_id,
);
die "No entity!" unless defined $entity;

my $os = $entity->find_field(field => 'perlos');
die "No OS!" unless defined $os;

$s->exit_zero unless exists($dispatch{$os});

$entity = $dispatch{$os}($s, $entity);

$s->update_entity(entity => $entity);

$s->exit_zero;

sub linux {
    my $s = shift;
    my $entity = shift;

    my $resolvconf = $s->run_command(command => 'cat /etc/resolv.conf');
    foreach my $line (split(/\n/, $resolvconf)) {
        if ($line =~ /^search/) {
            my @searchorder = split(/ /, $line);
            shift @searchorder;
            $entity->add_field(
                field => 'resolver-search',
                value => $_,
            ) foreach @searchorder;
        } elsif ($line =~ /^nameserver (.+)/) {
            my $nameserver = $1;
            $entity->add_field(
                field => 'nameserver',
                value => $nameserver,
            );
        }
    }
    return $entity;
}
